title: "Reduct Framework Docs"
remote_theme: just-the-docs/just-the-docs
color_scheme: "dark"
search_enabled: false

# Build settings
#theme: "just-the-docs"
#color_scheme: dark
#plugins:
#  - jekyll-feed